In [33]:
import scipy.io
import h5py
import numpy as np
import os

In [34]:
parent=r"E:\neurospark_mat\KA MODEL TRANSITION SESSIONS"
sessions=os.listdir(parent) 

In [35]:
for i,s in enumerate(sessions):
    print(f"{i}: {s}")
idx = int(input("Select session index: "))
session = sessions[idx]
data_path=os.path.join(parent,session)
mat_file= [f for f in os.listdir(data_path) if f.endswith(".mat")][0]
mat_file=os.path.join(data_path,mat_file)
# path=r"C:\__NeuroSpark_Liset_Dataset__\neurospark_mat\KA MODEL TRANSITION SESSIONS\Thy01uLED_hippo_2023-01-17_09-36-28_1558um\neurospark.mat"
try:
    mat_data = scipy.io.loadmat(mat_file)
    print("File loaded with scipy.io")
except:
    mat_data = h5py.File(mat_file, 'r')
    print("File loaded with h5py")

0: Calb01uLED_hippo_2022-12-21_13-10-56_1558um
1: Calb01uLED_hippo_2022-12-21_14-12-20_1558um
2: Calb01uLED_hippo_2022-12-21_17-39-06_1558um
3: Calb01uLED_hippo_2022-12-22_09-52-13_1558um
4: Calb01uLED_hippo_2023-01-09_11-28-01_1558um
5: Calb01uLED_hippo_2023-01-12_10-19-17_1558um
6: Calb01uLED_hippo_2023-01-13_09-56-47_1558um
7: KA MODEL SESSIONS.xlsx
8: Thy01uLED_hippo_2022-12-21_merged
9: Thy01uLED_hippo_2022-12-22_merged
10: Thy01uLED_hippo_2023-01-09_12-45-53_1558um
11: Thy01uLED_hippo_2023-01-17_09-36-28_1558um
12: Thy01uLED_hippo_2023-01-17_merged
File loaded with h5py


In [36]:
print(list(mat_data.keys()))
neurospark = mat_data['neurosparkmat'] 

['#refs#', '#subsystem#', 'neurosparkmat']


In [37]:
print(neurospark['IISs'])
print(neurospark['IISs']["times"])

# 1. Get the reference object (this is what you have already done)
ref = neurospark['IISs']['times'][1, 0]
print(ref)
# 2. Use the reference to look up the actual data in the file
#    This is the key step.
data_object = mat_data[ref]
print(data_object)
actual_data = data_object[()]
print(actual_data.shape)
data=np.array(actual_data)
flat=data.flatten()
print(flat)
len(flat)

print(neurospark["IISs"]["SD"])
SD = np.array(neurospark['IISs']['SD'])
print(SD)

<HDF5 group "/neurosparkmat/IISs" (2 members)>
<HDF5 dataset "times": shape (4, 1), type "|O">
<HDF5 object reference>
<HDF5 dataset "c": shape (2799, 1), type "<f8">
(2799, 1)
[ 175.03316667  505.095       515.75       ... 3600.198      3600.22533333
 3600.45066667]
<HDF5 dataset "SD": shape (1, 1), type "<f8">
[[8.]]


In [40]:
print(neurospark['seizure']["times"])
print(neurospark['seizure']["times"][0,0])
ref= neurospark['seizure']['times'][3, 0]
data_object = mat_data[ref]
print(data_object)
actual_data = data_object[()]
print(actual_data.shape)
# data=np.array(actual_data)
# print(neurospark['IISs']["times"])
print(actual_data)
thrRate=np.array(neurospark['seizure']['thrRate'])
print(thrRate)
thrRate=thrRate.squeeze()
print(thrRate)
print(actual_data.T)
print(actual_data.T.shape)

<HDF5 dataset "times": shape (4, 1), type "|O">
<HDF5 object reference>
<HDF5 dataset "i": shape (2, 11), type "<f8">
(2, 11)
[[ 520.  990. 1475. 1945. 2255. 2950. 3020. 3100. 3260. 3450. 3555.]
 [ 530. 1010. 1515. 2010. 2330. 2960. 3030. 3110. 3275. 3460. 3600.]]
[[10.]]
10.0
[[ 520.  530.]
 [ 990. 1010.]
 [1475. 1515.]
 [1945. 2010.]
 [2255. 2330.]
 [2950. 2960.]
 [3020. 3030.]
 [3100. 3110.]
 [3260. 3275.]
 [3450. 3460.]
 [3555. 3600.]]
(11, 2)


In [10]:
print(neurospark['channels'])
ref = neurospark['channels']
channels = np.array(ref)   # shape (40, 1)
channels = channels.flatten()

print(channels.shape)
print(channels[:10])  # first 10 channels
# channels=mat_data[ref]


<HDF5 dataset "channels": shape (43, 1), type "<f8">
(43,)
[25. 21. 24. 28. 26. 22. 23. 27. 29. 17.]


In [17]:
for i,s in enumerate(sessions):
    print(f"{i}: {s}")
idx = int(input("Select session index: "))
session = sessions[idx]
data_path=os.path.join(parent,session)
mat_file= [f for f in os.listdir(data_path) if f.endswith(".mat")][0]
mat_file=os.path.join(data_path,mat_file)
# path=r"C:\__NeuroSpark_Liset_Dataset__\neurospark_mat\KA MODEL TRANSITION SESSIONS\Thy01uLED_hippo_2023-01-17_09-36-28_1558um\neurospark.mat"
try:
    mat_data = scipy.io.loadmat(mat_file)
    print("File loaded with scipy.io")
except:
    mat_data = h5py.File(mat_file, 'r')
    print("File loaded with h5py")

0: Calb01uLED_hippo_2022-12-21_13-10-56_1558um
1: Calb01uLED_hippo_2022-12-21_14-12-20_1558um
2: Calb01uLED_hippo_2022-12-21_17-39-06_1558um
3: Calb01uLED_hippo_2022-12-22_09-52-13_1558um
4: Calb01uLED_hippo_2023-01-09_11-28-01_1558um
5: Calb01uLED_hippo_2023-01-12_10-19-17_1558um
6: Calb01uLED_hippo_2023-01-13_09-56-47_1558um
7: KA MODEL SESSIONS.xlsx
8: Thy01uLED_hippo_2022-12-21_merged
9: Thy01uLED_hippo_2022-12-22_merged
10: Thy01uLED_hippo_2023-01-09_12-45-53_1558um
11: Thy01uLED_hippo_2023-01-17_09-36-28_1558um
12: Thy01uLED_hippo_2023-01-17_merged
File loaded with h5py
